### ISSUE TITLE
Regarding a detail in the fitting code

### ISSUE THREAD

**Issue by yunfan0621** [HavenFeng/photometric_optimization#10]
Hi, thanks for sharing this great work!

I have a little question regarding the main fitting code in the following line:
https://github.com/HavenFeng/photometric_optimization/blob/44fc6e01ce962f5d29bcef48bfe0df61828f5de3/photometric_fitting.py#L42

Why hard code cam[:, 0] to 5. ? Is this a default setting in FLAME so that it may benefit the convergence of the fitting process?

Thank you!

**Comment by shriyakak** [comment]
Hi, 
I also have the same question. Did you get to know the answer @yunfan0621?

**Comment by HavenFeng** [comment]
sorry for the late reply, we hardcoded the z distance of the camera to make sure the camera view can always see the object. Since we used an orthographic projection camera, this z distance value doesn't really matter.
