### ISSUE TITLE
What are "Full Landmarks"?

### ISSUE THREAD

**Issue by D0miH** [HavenFeng/photometric_optimization#4]
Hi,

I looked through the code and tried to comprehend how the dynamic landmarks are calculated. Additionally to the indices and the barycentric coordinates of the dynamic and static landmarks I found `full_lmk_faces_idx` and `full_lmk_bary_coords` in the code.
What are these landmarks and why are they needed in addition to the dynamic and static landmarks?

Best,
Dominik

**Comment by HavenFeng** [comment]
the 'full_lmk_faces_idx' and 'full_lmk_bary_coords' are the 51 static lmks plus the complete 17 jawline lmks, we only use them for the 3d lmks visualization.

**Comment by D0miH** [comment]
Ok, thank you very much! :)
