### ISSUE TITLE
Perspective projection 

### ISSUE THREAD

**Issue by SavvaI** [HavenFeng/photometric_optimization#6]
Are there any specific reasons for you using orthogonal projection instead of perspective? I have tried reconstruction of the head from the photo with your code, and it doesn't align well with the ground truth point cloud obtained through photogrammetry. I suspect the problem is with the orthogonal projection. So, my question is, can I expect it to work after replacing an ortho projection with the perspective one. 
Thanks for the great work!

**Comment by HavenFeng** [comment]
Hi, there's no specific reason for choosing the orthogonal projection. In general, perspective projection requires intrinsic parameters, however, there's nowhere to get such information for in-the-wild scenarios. (people usually set a big focal length, which leads to almost no perspective effects).
