### ISSUE TITLE
 Basel Face Model (BFM) to FLAME

### ISSUE THREAD

**Issue by saikiran321** [HavenFeng/photometric_optimization#8]
How did you fit BFM model to FLAME? I have tried fitting a Flame mean shape to BFM mean shape, but couldn't find good shape parameters for FLAME model.

If you can give me some info on this it would be helpful.

**Comment by HavenFeng** [comment]
It requires a coupled registration process, it also may depend on your optimizer choice, we use L-BFGS-B for our fitting process.

**Comment by HavenFeng** [comment]
you can also check this repo: https://github.com/TimoBolkart/BFM_to_FLAME

**Comment by narikp** [comment]
Thanks, this helps a lot.

**Comment by saikiran321** [comment]
Thanks, this helps very much
